#!/usr/bin/bash


####################################
# Name      : Weasel Framework
# Developer : iamramahibrah
####################################




info()
{
  clear
  echo
  echo -e -n "
  [+]  WEASEL FRAMEWORK \e[1;32m ● \e[0m


    \e[1;32m*********\e[0m
    Tool name : Weasel framework
    Warranty  : MIT
    Developer : iamramahibrah
    Purpose   : Vulnerability Scan & Security audit
    Since     : 2021 
    Version   : 0.1

    usage  (options) -Help
    \e[1;32m*********\e[0m"
}
info

function help()
{
  echo -e "

      Options:

          --css-injection     |  Scan for CSS Injection Vulnerability
          --cve-scanner       |  Scan for Common Vulnerability Exposure *NOTE: scan all vulnerabilities available in target*
          --xss-vuln          |  XSS Vulnerability scanning 
          --heartbleed        |  Scan for SSL-Heartbleed Vulnerability
          --services          |  Scan for Services and Versions "
}

function css()
{
  echo -e "

  [+] \e[33;1m CCS-INJECTION VULNERABILITY \e[0m
           Powered by Nmap
                      \e[1;32m****\e[0m"
  echo
  echo -e -n "   Enter \e[33;1mhost target\e[0m: "
  read host
ping -c1 -W1 -q $host &>/dev/null
status=$( echo $? )
if [[ $status == 0 ]] ; then
    echo -e " $host .... [\e[1;32m Connected\e[0m] "
    echo -e "$YELLOW scanning $host for CCS-INJECTION $NOCOLOR"
    sleep 1s
    nmap -p5432 --script ssl-ccs-injection $host
else
   echo -e " $host ....  [$RED Server Down $NOCOLOR] "
fi
}

function cve()
{
  echo -e "

  [+] \e[33;1m VULNERABILITY SCANNER \e[0m
           Powered by nmap
                      \e[1;32m****\e[0m"
  echo
  echo -e -n "   Enter \e[33;1mhost target\e[0m: "
  read host
ping -c1 -W1 -q $host &>/dev/null
status=$( echo $? )
if [[ $status == 0 ]] ; then
    echo -e " $host .... [\e[1;32m Connected\e[0m] "
    echo -e "$YELLOW scanning $host for vulnerabilities $NOCOLOR"
    sleep 1s
    nmap -sV -sC -vv --script vuln $host
else
   echo -e " $host ....  [$RED Server Down $NOCOLOR] "
fi
}



xss-par()
{
  echo -e "

  [+] \e[33;1m XSS AND PARAMETER ANALYSIS \e[0m
           Powered by sslscan
                      \e[1;32m****\e[0m"
  echo
  echo -e -n "   Enter \e[33;1mhost target\e[0m: "
  read host
ping -c1 -W1 -q $host &>/dev/null
status=$( echo $? )
if [[ $status == 0 ]] ; then
    echo -e " $host .... [$GREEN Connected$NOCOLOR ] "
    echo -e "$YELLOW scanning $host for XSS Parameter $NOCOLOR"
    sleep 1s
    nmap -p80 --script http-unsafe-output-escaping $host
else
   echo -e " $host ....  [$RED Server Down $NOCOLOR] "
fi
}




function heart()
{
  echo -e "

  [+] \e[33;1m HEARTBLEED VULNERABILITY SCANNER \e[0m
           Powered by nmap
                      \e[1;32m****\e[0m"
  echo
  echo -e -n "   Enter \e[33;1mhost target\e[0m: "
  read host
ping -c1 -W1 -q $host &>/dev/null
status=$( echo $? )
if [[ $status == 0 ]] ; then
    echo -e " $host .... [\e[1;32m Connected\e[0m] "
    echo -e "$YELLOW scanning $host for heartbleed vulnerabilities $NOCOLOR"
    sleep 1s
    nmap -d --script ssl-heartbleed --script-args vulns.showall -sV  $host
else
   echo -e " $host ....  [$RED Server Down $NOCOLOR] "
fi
}



serv()
{
  echo -e "

  [+] \e[33;1m SERVICES AND VERSIONS \e[0m
           Powered by nmap
                      \e[1;32m****\e[0m"
  echo
  echo -e -n "   Enter \e[33;1mhost target\e[0m: "
  read host
ping -c1 -W1 -q $host &>/dev/null
status=$( echo $? )
if [[ $status == 0 ]] ; then
    echo -e " $host .... [\e[33;1m Connected \e[0m ] "
    echo -e " scanning \e[33;1m $host  \e[0m  for services & versions \e[0m"
    sleep 1s
    nmap -sV $host
else
   echo -e " $host ....  [$RED Server Down $NOCOLOR] "
fi
}


while [ $# -gt 0 ]; do
  case "$1" in
    -Help)
      help
      ;;
    --css-injection)
      css
      ;;
    --cve-scanner)
      cve
      ;;
    --xss-vuln)
      xss-par
      ;;
    --heartbleed)
      heart
      ;;
    --services)
      serv
      ;;

    *)
      >&2 printf "Error: Invalid argument\n"
      exit 1
      ;;
  esac
  shift
done

