#!/usr/bin/bash


####################################
# Name      : Weasel Framework
# Developer : iamramahibrah
####################################




info()
{
  clear
  echo
  echo -e -n "
  [+]  WEASEL FRAMEWORK \e[1;32m ● \e[0m


    \e[1;32m*********\e[0m
    Tool name : Weasel framework
    Warranty  : MIT
    Developer : iamramahibrah
    Purpose   : Vulnerability Scan & Security audit
    Since     : 2021 
    Version   : 0.1

    usage  (options) -Help
    \e[1;32m*********\e[0m"
}
info

function help()
{
  echo -e "

      Options:

          --prev | Linux Privilege Escalation "
}

function lpe()
{

 echo -e "
 [+] \e[33;1m LINUX PRIVILEGE ESCALATION \e[0m [+]"
./lin/linpeas.sh -q
}


while [ $# -gt 0 ]; do
  case "$1" in
    -Help)
      help
      ;;
    --prev)
      lpe
      ;;

    *)
      >&2 printf "Error: Invalid argument\n"
      exit 1
      ;;
  esac
  shift
done

